version: '3.7'
services:
  interlink:
    build:
      context: ../../../
      dockerfile: docker/Dockerfile.interlink
    restart: always
    #network_mode: "host"
    ports:
    - 3000:3000
    volumes:
    - type: bind
      source: ./
      target: /etc/interlink
    environment:
    - INTERLINKCONFIGPATH=/etc/interlink/InterLinkConfig.yaml
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
  docker-sidecar:
    image: ghcr.io/intertwin-eu/interlink-sidecar-docker:0.0.2-pre1
    restart: always
    privileged: true
    cap_add:
    - SYS_ADMIN
    #network_mode: "host"
    ports:
    - 4000:4000
    environment:
    - INTERLINKCONFIGPATH=/etc/interlink/sidecarConfig.yaml
    volumes:
    - type: bind
      source: ./
      target: /etc/interlink
    - type: bind
      source: /var/run/docker.sock 
      target: /var/run/docker.sock 
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
