FROM python:3.11.7

# To avoid interaction with apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Install dev packages
RUN apt -y update && \
    apt -y install git wget nano less apt-transport-https
RUN apt -y install bat && \
    mkdir -p ~/.local/bin && ln -s /usr/bin/batcat ~/.local/bin/bat
RUN apt -y install zsh && \
    git clone https://github.com/jotyGill/ezsh ezsh && cd ezsh && ./install.sh -c && \
    sed -i 's/# zsh-autosuggestions/zsh-autosuggestions/g' /root/.config/ezsh/ezshrc.zsh && \
    sed -i 's/# git/git/g' /root/.config/ezsh/ezshrc.zsh

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install dev requirements
COPY requirements-dev.txt /tmp/pip-tmp/
RUN pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements-dev.txt

# Install app requirements
COPY requirements.txt /tmp/pip-tmp/
RUN pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp
