VKTokenFile: "$HOME/interLink/token"
InterlinkAddress: "http://XXX.XXX.XXX.XXX"
CommandPrefix: ""
ExportPodData: true
ServiceAccount: "interlink"
Namespace: "vk"
VerboseLogging: true
ErrorsOnlyLogging: false
CPU: 100
Memory: 128Gi
Pod: 100
