apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service-account.yaml

configMapGenerator:
  - name: vk-config-json
    files:
      - vk-cfg.json=vk-cfg.json
  - name: vk-config 
    files:
      - InterLinkConfig.yaml=InterLinkConfig.yaml